sudo: required
language: node_js
node_js:
    - '12.14.1'
install:
    - npm ci
matrix:
    fast_finish: true
    include:
        - name: 'npm audit'
          script:
              - npm run audit:ci
        - name: 'compile Typescript'
          script:
              - npm run build
        - name: 'lint'
          script:
              - npm run lint
        - name: 'test'
          script:
              - npm test