sequenceDiagram
    BlockThemeCli->>BlockThemeRegistry: publish
    BlockThemeRegistry-->>BlockThemeCli: blockId

    BlockThemeCli->>BlockThemeRegistry: update
    BlockThemeRegistry-->>BlockThemeCli: blockId
