name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: node-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install npm packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
